version: '3'
services:
  db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  mongo_data:
